### ISSUE TITLE
Deviance function for Poisson distribution

### ISSUE THREAD

**Issue by natsuhiko** [willtownes/scrna2019#4]
Hello,

I would like to make sure the deviance function for Poisson distribution is correct or not.

I saw 

```
2*sum(x*log(x/(sz*mu)),na.rm=TRUE)-2*sum(x-sz*mu)
```

in `util/function.R`, but I'm wondering if it is

```
2*sum(x*log(x/(sz*mu)),na.rm=TRUE)-2*sum(x-mu)
```
Best regards,
Natsuhiko

**Comment by willtownes** [comment]
Hi thanks for your interest! Yes the [first one](https://github.com/willtownes/scrna2019/blob/master/util/functions.R#L87) is correct. I probably should not have used "mu" in that function though, as you can see in the goodness-of-fit function that calls it `fit$deviance<-poisson_deviance(x,sum(x)/sum(sz),sz)` so the `mu` parameter is really not the mean but a rate parameter. I went ahead and renamed it `lambda` so hopefully it will be less confusing for other users.

By the way, if you are planning to use any of these functions please consider trying the [scry bioconductor package](https://bioconductor.org/packages/release/bioc/html/scry.html) instead as it is more updated and handles a wider variety of data types.
