### ISSUE TITLE
A question about your GLMPCA function

### ISSUE THREAD

**Issue by liuzhe93** [willtownes/scrna2019#5]
Dear authors,

My name is Liu zhe, I have a question about your R package. 
My data has the **batch effect**, so I need to remove this noise for better clustering. The traditional runPCA() function is not satisfied my requirement, so I search on the internet and find your R package is very suitable for my proposal. However, I encounter a question when I perform the downstream analysis.

This is my scripts and results:
_the deviance drops sharply after about 1,000 genes.
the following genes are discarded because they are little information.
glioma.combined.sce is a S4 object named "SingleCellExperiment" class_
> glioma.combined.sce<-glioma.combined.sce[1:1000, ]
> glioma.combined.sce<-GLMPCA(glioma.combined.sce, 2, assay="counts")
> glioma.combined.sce
class: SingleCellExperiment 
dim: 1000 49237 
metadata(1): glmpca
assays(2): counts logcounts
rownames(1000): SPP1 MALAT1 ... EIF3L SMS
rowData names(6): vst.mean vst.variance ... vst.variable
  binomial_deviance
colnames(49237): AAACCCAAGCCATTGT-1_1 AAACCCAAGTAGTCCT-1_1 ...
  TTTGTTGTCCTGTAGA-1_2 TTTGTTGTCTCCATAT-1_2
colData names(11): orig.ident nCount_RNA ... label ident
reducedDimNames(1): GLMPCA
altExpNames(0):

I think I got the right results. However, I got the question when I translated this object to a "Seurat" object. 
> glioma.combined.seurat <- as.Seurat(glioma.combined.sce, counts = "counts", data = "logcounts")
Error in validObject(.Object) : 
  invalid class “DimReduc” object: invalid object for slot "cell.embeddings" in class "DimReduc": got class "data.frame", should be or extend class "matrix"

_The error messages indicate that SingleCellExperiment object is a data.frame, not a matrix; but Seurat requires that cell embeddings (reducedDims in the SCE world) are of class matrix._ So could you give me some suggestions for completing this transformation?

Thanks for your kind help.

Best wishes,
Zhe

**Comment by willtownes** [comment]
Hi Zhe, thanks for pointing this out. We can certainly change the stored reducedDims to be a matrix instead of a data frame. I have created a new issue to work on this in the main glmpca repo: willtownes/glmpca/#28 . Please leave further comments there as this repo is for archival purposes only.

**Comment by willtownes** [comment]
Also in the meantime, you could always just manually convert the reducedDims to a matrix by extracting it and then putting it back in, see for example: https://rdrr.io/bioc/SingleCellExperiment/man/reducedDims.html

**Comment by liuzhe93** [comment]
> Also in the meantime, you could always just manually convert the reducedDims to a matrix by extracting it and then putting it back in, see for example: https://rdrr.io/bioc/SingleCellExperiment/man/reducedDims.html

Will Townes, thank you so much.
